# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2026 The Birthmark Standard Foundation

"""Initial schema with normalized submission_server_id

Revision ID: 79d5e2ca3acd
Revises: 
Create Date: 2025-12-15 20:59:39.747437+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d5e2ca3acd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('block_height', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('block_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('previous_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('validator_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('block_height')
    )
    op.create_index('idx_blocks_height', 'blocks', ['block_height'], unique=False)
    op.create_index(op.f('ix_blocks_block_hash'), 'blocks', ['block_hash'], unique=True)
    op.create_table('node_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('current_block_height', sa.BigInteger(), nullable=False),
    sa.Column('total_hashes', sa.BigInteger(), nullable=False),
    sa.Column('genesis_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('last_block_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('tx_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('block_height', sa.BigInteger(), nullable=False),
    sa.Column('submission_server_id', sa.String(length=255), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_height'], ['blocks.block_height'], ),
    sa.PrimaryKeyConstraint('tx_id')
    )
    op.create_index('idx_tx_block', 'transactions', ['block_height'], unique=False)
    op.create_index(op.f('ix_transactions_block_height'), 'transactions', ['block_height'], unique=False)
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=True)
    op.create_table('image_hashes',
    sa.Column('image_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('block_height', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('parent_image_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('modification_level', sa.Integer(), nullable=False),
    sa.Column('gps_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_height'], ['blocks.block_height'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.tx_id'], ),
    sa.PrimaryKeyConstraint('image_hash')
    )
    op.create_index('idx_hashes_block', 'image_hashes', ['block_height'], unique=False)
    op.create_index('idx_hashes_modification_level', 'image_hashes', ['modification_level'], unique=False)
    op.create_index('idx_hashes_parent', 'image_hashes', ['parent_image_hash'], unique=False)
    op.create_index('idx_hashes_timestamp', 'image_hashes', ['timestamp'], unique=False)
    op.create_index(op.f('ix_image_hashes_block_height'), 'image_hashes', ['block_height'], unique=False)
    op.create_index(op.f('ix_image_hashes_parent_image_hash'), 'image_hashes', ['parent_image_hash'], unique=False)
    op.create_index(op.f('ix_image_hashes_tx_id'), 'image_hashes', ['tx_id'], unique=False)
    op.create_table('modification_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_image_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('final_image_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('modification_level', sa.Integer(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_height', sa.Integer(), nullable=True),
    sa.Column('final_width', sa.Integer(), nullable=True),
    sa.Column('final_height', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.String(length=255), nullable=False),
    sa.Column('plugin_version', sa.String(length=50), nullable=False),
    sa.Column('authority_type', sa.String(length=50), nullable=False),
    sa.Column('initialized_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.tx_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mod_final', 'modification_records', ['final_image_hash'], unique=False)
    op.create_index('idx_mod_level', 'modification_records', ['modification_level'], unique=False)
    op.create_index('idx_mod_original', 'modification_records', ['original_image_hash'], unique=False)
    op.create_index('idx_mod_software', 'modification_records', ['software_id'], unique=False)
    op.create_index(op.f('ix_modification_records_final_image_hash'), 'modification_records', ['final_image_hash'], unique=True)
    op.create_index(op.f('ix_modification_records_original_image_hash'), 'modification_records', ['original_image_hash'], unique=False)
    op.create_index(op.f('ix_modification_records_software_id'), 'modification_records', ['software_id'], unique=False)
    op.create_table('pending_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('modification_level', sa.Integer(), nullable=False),
    sa.Column('parent_image_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('manufacturer_authority_id', sa.String(length=100), nullable=False),
    sa.Column('camera_token_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('gps_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('sma_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('validation_result', sa.String(length=50), nullable=True),
    sa.Column('tx_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.tx_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_modification_level', 'pending_submissions', ['modification_level'], unique=False)
    op.create_index('idx_pending_parent_hash', 'pending_submissions', ['parent_image_hash'], unique=False)
    op.create_index('idx_pending_transaction_id', 'pending_submissions', ['transaction_id'], unique=False)
    op.create_index('idx_pending_validated', 'pending_submissions', ['sma_validated'], unique=False)
    op.create_index(op.f('ix_pending_submissions_image_hash'), 'pending_submissions', ['image_hash'], unique=False)
    op.create_index(op.f('ix_pending_submissions_modification_level'), 'pending_submissions', ['modification_level'], unique=False)
    op.create_index(op.f('ix_pending_submissions_parent_image_hash'), 'pending_submissions', ['parent_image_hash'], unique=False)
    op.create_index(op.f('ix_pending_submissions_sma_validated'), 'pending_submissions', ['sma_validated'], unique=False)
    op.create_index(op.f('ix_pending_submissions_transaction_id'), 'pending_submissions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_submissions_transaction_id'), table_name='pending_submissions')
    op.drop_index(op.f('ix_pending_submissions_sma_validated'), table_name='pending_submissions')
    op.drop_index(op.f('ix_pending_submissions_parent_image_hash'), table_name='pending_submissions')
    op.drop_index(op.f('ix_pending_submissions_modification_level'), table_name='pending_submissions')
    op.drop_index(op.f('ix_pending_submissions_image_hash'), table_name='pending_submissions')
    op.drop_index('idx_pending_validated', table_name='pending_submissions')
    op.drop_index('idx_pending_transaction_id', table_name='pending_submissions')
    op.drop_index('idx_pending_parent_hash', table_name='pending_submissions')
    op.drop_index('idx_pending_modification_level', table_name='pending_submissions')
    op.drop_table('pending_submissions')
    op.drop_index(op.f('ix_modification_records_software_id'), table_name='modification_records')
    op.drop_index(op.f('ix_modification_records_original_image_hash'), table_name='modification_records')
    op.drop_index(op.f('ix_modification_records_final_image_hash'), table_name='modification_records')
    op.drop_index('idx_mod_software', table_name='modification_records')
    op.drop_index('idx_mod_original', table_name='modification_records')
    op.drop_index('idx_mod_level', table_name='modification_records')
    op.drop_index('idx_mod_final', table_name='modification_records')
    op.drop_table('modification_records')
    op.drop_index(op.f('ix_image_hashes_tx_id'), table_name='image_hashes')
    op.drop_index(op.f('ix_image_hashes_parent_image_hash'), table_name='image_hashes')
    op.drop_index(op.f('ix_image_hashes_block_height'), table_name='image_hashes')
    op.drop_index('idx_hashes_timestamp', table_name='image_hashes')
    op.drop_index('idx_hashes_parent', table_name='image_hashes')
    op.drop_index('idx_hashes_modification_level', table_name='image_hashes')
    op.drop_index('idx_hashes_block', table_name='image_hashes')
    op.drop_table('image_hashes')
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_height'), table_name='transactions')
    op.drop_index('idx_tx_block', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('node_state')
    op.drop_index(op.f('ix_blocks_block_hash'), table_name='blocks')
    op.drop_index('idx_blocks_height', table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
